global:
  scrape_interval:     10s
  evaluation_interval: 20s

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"

scrape_configs:
  - job_name: 'prometheus'
#    scheme: https
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9100']

  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [prometheus]
    honor_labels: true
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:19999']
